#Input file name - to be implemented fully later on

sampleNames: #Enter the part BEFORE file extension (ex. 'data.h5ad' should be entered as 'data')
# - GTEx_v5-Adipose_-_Subcutaneous
# - GTEx_v5-Adipose_-_Visceral_Omentum
# - GTEx_v5-Muscle_-_Skeletal
# - GTEx_v8-Adipose_-_Subcutaneous
# - GTEx_v8-Adipose_-_Visceral_Omentum
# - GTEx_v8-Muscle_-_Skeletal
# - GTEx_GTEx_v8-Skin_-_Sun_Exposed_Lower_leg
# - GTEx_GTEx_v5-Skin_-_Sun_Exposed_Lower_leg
# - GTEx_GTEx_v8-Skin_-_Not_Sun_Exposed_Suprapubic
# - GTEx_GTEx_v5-Skin_-_Not_Sun_Exposed_Suprapubic
- GTEx_Wiedemann_v5-Skin_-_Not_Sun_Exposed_Suprapubic
- GTEx_Wiedemann_v8-Skin_-_Sun_Exposed_Lower_leg
- GTEx_Wiedemann_v5-Skin_-_Sun_Exposed_Lower_leg
- GTEx_Wiedemann_v8-Skin_-_Not_Sun_Exposed_Suprapubic
# - GTEx_v8-Adipose_-_Subcutaneous
# - GTEx_v8-Adipose_-_Visceral_Omentum
# - GTEx_v8-Adrenal_Gland
# - GTEx_v8-Artery_-_Aorta
# - GTEx_v8-Artery_-_Coronary
# - GTEx_v8-Artery_-_Tibial
# - GTEx_v8-Bladder
# - GTEx_v8-Brain_-_Amygdala
# - GTEx_v8-Brain_-_Anterior_cingulate_cortex_BA24
# - GTEx_v8-Brain_-_Caudate_basal_ganglia
# - GTEx_v8-Brain_-_Cerebellar_Hemisphere
# - GTEx_v8-Brain_-_Cerebellum
# - GTEx_v8-Brain_-_Cortex
# - GTEx_v8-Brain_-_Frontal_Cortex_BA9
# - GTEx_v8-Brain_-_Hippocampus
# - GTEx_v8-Brain_-_Hypothalamus
# - GTEx_v8-Brain_-_Nucleus_accumbens_basal_ganglia
# - GTEx_v8-Brain_-_Putamen_basal_ganglia
# - GTEx_v8-Brain_-_Spinal_cord_cervical_c-1
# - GTEx_v8-Brain_-_Substantia_nigra
# - GTEx_v8-Breast_-_Mammary_Tissue
# - GTEx_v8-Cells_-_Cultured_fibroblasts
# - GTEx_v8-Cells_-_EBV-transformed_lymphocytes
# - GTEx_v8-Cervix_-_Ectocervix
# - GTEx_v8-Cervix_-_Endocervix
# - GTEx_v8-Colon_-_Sigmoid
# - GTEx_v8-Colon_-_Transverse
# - GTEx_v8-Esophagus_-_Gastroesophageal_Junction
# - GTEx_v8-Esophagus_-_Mucosa
# - GTEx_v8-Esophagus_-_Muscularis
# - GTEx_v8-Fallopian_Tube
# - GTEx_v8-Heart_-_Atrial_Appendage
# - GTEx_v8-Heart_-_Left_Ventricle
# - GTEx_v8-Kidney_-_Cortex
# - GTEx_v8-Kidney_-_Medulla
# - GTEx_v8-Liver
# - GTEx_v8-Lung
# - GTEx_v8-Minor_Salivary_Gland
# - GTEx_v8-Muscle_-_Skeletal
# - GTEx_v8-Nerve_-_Tibial
# - GTEx_v8-Ovary
# - GTEx_v8-Pancreas
# - GTEx_v8-Pituitary
# - GTEx_v8-Prostate
# - GTEx_v8-Skin_-_Not_Sun_Exposed_Suprapubic
# - GTEx_v8-Skin_-_Sun_Exposed_Lower_leg
# - GTEx_v8-Small_Intestine_-_Terminal_Ileum
# - GTEx_v8-Spleen
# - GTEx_v8-Stomach
# - GTEx_v8-Testis
# - GTEx_v8-Thyroid
# - GTEx_v8-Uterus
# - GTEx_v8-Vagina
# - GTEx_v8-Whole_Blood

seededRun: 0 #Use if you want this run of the pipeline to be reproducible (0-1)
realBulk: 0  #Use if you are going to test with real data with known proportions (0-1)
realBulk-noProp: 1 #Use to get results only if no ground truths are present


cores:
  pbulks: 32
  c_gen: 32
  CDSeq: 16
  CPM: 16
  CIBERSORT: 3
  bseqsc: 3
  DWLS: 16
  debCAM_unsupervised: 30
  scaleTransform: 32

mem_gb: #Will be converted to MB

  resultsExp: 5 #Only needed at last step
  minorOps: 50 #Will be used for all operations that require relatively less memory
  pbulks: 300
  scaleTransform: 300
  c_gen: 300
  CDSeq: 300
  Bisque: 300
  CPM: 300
  DWLS: 300
  MuSiC: 300
  SCDC: 300
  TIMER: 300
  bseqsc: 300
  MOMF: 300




#pbulk parameters below
pbulkParam:
  pbulkMode: 2  #Different mode for building pbulks
  cellCount: 2000  #How many cells should be used to create a bulk sample
  nSamples: 1000  #How many different samples should be generated
  propVar: 500 #Variances inbetween proportions, check vignette (EFFECTIVE IN MODE 2 ONLY, enter negative value to switch to min max prop mode)
  sampleCT: 0 #Sampling for cell types allowed or not (1 or 0) (EFFECTIVE IN MODE 2 ONLY)




#Available tests in Seurat:
#   "wilcox"
#   "bimod"
#   "roc"
#   "t"
#   "negbinom"
#   "poisson"
#   "LR"
#   "MAST"
#   "DESeq2"

#Normalizations available in Seurat:
#   LogNormalize
#   CLR # NOT WORKING, DO NOT USE
#   RC
refgenDgeParam:
    test_1: 'bimod'
    test_2: 'wilcox'
    seuratNorm: 'LogNormalize'


#params for scale_transform

#Transform
#   none
#   log
#   sqrt
#   vst (requires high memory)


#scaleC
#   none
#   column
#   row
#   mean
#   column_z-score
#   global_z-score
#   column_min-max
#   global_min-max
#   LogNormalize
#   QN
#   TMM
#   SCTransform (sc-specific)
#   scater (sc-specific)
#   scran (sc-specific)
#   Linnorm (sc-specific)

#scaleT
#   none
#   column
#   row
#   mean
#   column_z-score
#   global_z-score
#   column_min-max
#   global_min-max
#   LogNormalize
#   QN
#   TMM
#   UQ
#   median_ratios

stParam:
  scaleC: SCTransform
  scaleT: TMM
  transform: none
  scaleFirst: 1 #1 = scale first, 0 = transform first


### METHODS ###
## Bulk
# CIBERSORT
# DeconRNASeq
# OLS
# NNLS
# FARDEEP
# RLR
# DCQ
# elasticNET
# lasso
# ridge
# EPIC
# DSA
# ssKL
# ssFrobenius
# dtangle
# deconf
# proportionsInAdmixture
# EpiDISH
# debCAM_unsupervised
# debCAM_marker
# debCAM_C1
# CDSeq

## SC
# MuSiC
# Bisque
# DWLS
# SCDC
# bseqsc
# CPM
# TIMER

# Add or delete//comment the methods below to run them.
deconMethods:
  - FARDEEP
  - EpiDISH
  - DWLS

### RESULTS ###

## Implemented metrics:
#rmse        (Root Mean Squared Error)
#mdist      (Minkowski Distance, use p=2 for euclidean)
#dcor        (Distance correlation)
#pcor        (Pearson correlation)
#avgcos     (Average cosine similarity, considering each sample as vector of genes)
#mae         (Mean Absolute Error)
#R2          (R-squared)
resMetrics:
  - rmse
  - mdist
  - dcor
  - pcor
  - avgcos
  - mae
  - r2
minkowski_p: 2
